name: pulsator
description: "Pulse animation for Flutter."
version: 1.0.0
homepage: https://github.com/booncol/pulsator

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true